export const GOLD_KHANJAR_TITLE = "ROLEX GOLD KHANJAR Ref.1665/0 — Client Demo";

export const GOLD_KHANJAR_NARRATION =
  "1970年代、オマーンは新しい時代の入口に立っていました。国を率いたカーブース国王は、英国との結びつきの中で、功労者へ贈り物を届けます。その製作を託されたのが、英国王室とも縁の深い名門ジュエラー、アスプレイでした。選ばれたのはロレックス。文字盤には、オマーンの威信を象徴する金色のカンジャル。これは装飾ではありません。厚みある紋章、ASPREYの刻印、裏蓋内部のシリアル、そして500万番台の番号。今回の1665/0には、国家と英国、そして時計製造の歴史が交差した証が、残されています。GOLD KHANJAR。時を超え、物語を宿す一本です。";

export const GOLD_KHANJAR_ASSETS: Record<string, string> = {
  "1.jpg": "Front Hero",
  "MG_1220.jpg": "Dial Gold Khanjar",
  "MG_1204.jpg": "Caseback ASPREY",
  "MG_1202.jpg": "Inside Caseback Serial 1665",
  "MG_1200.jpg": "Movement",
  "MG_1216.jpg": "Crown Profile",
  "MG_1212.jpg": "Bracelet Clasp",
};

export const GOLD_KHANJAR_SCENES = [
  [6, "CityEraEstablishing", "1970年代オマーン", "1970s\nOMAN", "1970s", "OMAN", "1970s Muscat, Oman at dusk, authentic low whitewashed buildings between rugged mountains and the sea, warm dusty atmosphere, restrained archival documentary realism, sparse period vehicles far in the distance, no readable text, no logos, no emblems, no watches, no modern skyline", "slow aerial-to-street push", "wide establishing shot", "late afternoon amber haze", "dust in the air and subtle distant movement", "sandstone, charcoal and muted amber", "restrained dissolve"],
  [7, "HistoricalCharacter", "国家と権威", "A NEW ERA", null, null, "1970s Omani palace interior, dignified Middle Eastern statesman seen from behind walking through a shadowed colonnade, historically appropriate white dishdasha and restrained turban, quiet authority, photorealistic historical documentary, no identifiable real person, no readable text, no logos, no royal crest, no watches", "measured tracking shot from behind", "medium-wide silhouette", "warm window shafts through dust", "slow deliberate walk and fabric movement", "dark wood, limestone and subdued gold", "dust dissolve"],
  [8, "HistoricalEvent", "オマーンと英国", "OMAN × UNITED KINGDOM", null, null, "1970s diplomatic meeting room connecting Oman and Britain, two senior officials in period-correct attire exchanging a restrained greeting beside a mahogany table, cinematic historical documentary, faces natural and understated, no readable documents, no text, no logos, no emblems, no watches, no modern electronics", "slow lateral dolly", "medium two-shot", "soft overcast window light and warm practicals", "subtle handshake and respectful body language", "mahogany, cream and deep green", "motion matched cut"],
  [9, "HistoricalEvent", "功労者への贈答", "A SPECIAL GIFT", null, null, "1970s ceremonial gift presentation in a refined Omani interior, gloved attendant placing a closed unbranded dark leather presentation box into the hands of a recipient, quiet state occasion, premium photorealistic documentary, no object visible inside the box, no readable text, no logos, no crest, no watch, anatomically correct hands", "slow controlled push toward the exchange", "close medium detail", "single warm key with soft falloff", "one careful handover only", "black leather, walnut and restrained gold", "subtle light transition"],
  [10, "HistoricalEvent", "英国の名門ジュエラー", "ASPREY\nLONDON", null, null, "1970s luxury London jeweller interior inspired by Bond Street craftsmanship, mahogany display cabinetry, velvet trays, brass lamps, a master craftsperson preparing an unbranded presentation box, premium archival cinema, no readable shop sign, no text, no logos, no emblems, no watch product visible, no modern objects", "slow dolly through foreground glass reflections", "wide-to-medium interior", "warm tungsten pools in a dark room", "subtle craft movement and rack focus", "burgundy, walnut, brass and black", "restrained dissolve"],
  [11, "ProductHero", "選ばれたロレックス", "ROLEX Ref.1665/0", null, null, "Provided original product photograph only; preserve every product detail exactly.", "slow diagonal dolly", "full product hero", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [12, "WatchMacro", "文字盤", "GOLD KHANJAR", null, null, "Provided original product photograph only; preserve every product detail exactly.", "macro push toward the dial", "dial macro", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [13, "ProductHero", "カンジャル", "THE EMBLEM", null, null, "Provided original product photograph only; preserve every product detail exactly.", "controlled crop toward the emblem", "emblem detail", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [14, "ProductHero", "裏蓋", "ASPREY", null, null, "Provided original product photograph only; preserve every product detail exactly.", "slow light sweep", "caseback macro", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [15, "ProductHero", "シリアル", "SERIAL / 1665", null, null, "Provided original product photograph only; preserve every product detail exactly.", "measured vertical drift", "engraving macro", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [16, "WatchMacro", "ムーブメント", "5,000,000 SERIES", null, null, "Provided original product photograph only; preserve every product detail exactly.", "subtle rack-focus simulation", "movement macro", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [17, "ProductHero", "ケースとリューズ", "CROWN / CASE", null, null, "Provided original product photograph only; preserve every product detail exactly.", "slow side-profile dolly", "case profile", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [18, "ProductHero", "ブレスレット", "BRACELET / CLASP", null, null, "Provided original product photograph only; preserve every product detail exactly.", "controlled pan across brushed steel", "clasp macro", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [19, "ProductHero", "最終商品カット", "GOLD KHANJAR", null, null, "Provided original product photograph only; preserve every product detail exactly.", "slow final hero push", "hero close-up", "controlled luxury studio light", "camera and light motion only", "neutral steel, black and restrained gold", "restrained dissolve"],
  [20, "Ending", "ブランドエンド", "", null, null, "Pure black luxury brand ending with minimal motion and no product image.", "minimal fade", "black ending", "black", "near stillness", "black", "fade to black"],
] as const;

export const GOLD_KHANJAR_STATIC_FILES = Array.from({ length: 10 }, (_, index) => `scene-${index + 11}.mp4`);
